SELECT * FROM TB_PIZZA
LEFT JOIN TB_PEDIDO_PIZZA
ON TB_PIZZA.ID_PIZZA = TB_PEDIDO_PIZZA.ID_PIZZA;


SELECT A.NOME, B.ID_PEDIDO FROM TB_PIZZA A
LEFT JOIN TB_PEDIDO_PIZZA B
ON A.ID_PIZZA = B.ID_PIZZA;

SELECT A.NOME, D.NOME FROM TB_PIZZA A
LEFT JOIN TB_PEDIDO_PIZZA B ON A.ID_PIZZA = B.ID_PIZZA
LEFT JOIN TB_PEDIDO C ON C.ID_PEDIDO = B.ID_PEDIDO
LEFT JOIN TB_CLIENTE D ON D.ID_CLIENTE = C.ID_CLIENTE

--PRECO MEDIO
SELECT AVG(PRECO) FROM TB_PEDIDO;

-- SELECIONE TUDO DE TB_PEDIDO ONDE SEJA MAIOR QUE O PRECO MEDIO
SELECT * FROM TB_PEDIDO WHERE PRECO > (SELECT AVG(PRECO) FROM TB_PEDIDO);

SELECT * FROM TB_PEDIDO;

SELECT ID_CLIENTE FROM TB_PEDIDO WHERE TIPO_ENTREGA LIKE '%Retirada no balcão%';

SELECT NOME FROM TB_CLIENTE WHERE ID_CLIENTE
IN (SELECT ID_CLIENTE FROM TB_PEDIDO WHERE TIPO_ENTREGA LIKE '%Retirada no balcão%')

