SELECT * FROM TB_PEDIDO

SELECT * FROM TB_CLIENTE

-- PEGA O QUE TEM EM AMBAS AS TABELAS
SELECT * FROM TB_PEDIDO
INNER JOIN TB_CLIENTE
ON TB_PEDIDO.ID_CLIENTE = TB_CLIENTE.ID_CLIENTE

--PEGA TUDO ENTRE TABELA
SELECT * FROM TB_PEDIDO
FULL OUTER JOIN TB_CLIENTE
ON TB_PEDIDO.ID_CLIENTE = TB_CLIENTE.ID_CLIENTE

--PEGA TUDO ENTRE TABELA COM ELIAS
SELECT * FROM TB_PEDIDO TBS
FULL OUTER JOIN TB_CLIENTE TBC
ON TBS.ID_CLIENTE = TBC.ID_CLIENTE;

SELECT TBP.ID_PEDIDO, TBC.NOME FROM TB_PEDIDO TBS
FULL OUTER JOIN TB_CLIENTE TBC
ON TBS.ID_CLIENTE = TBC.ID_CLIENTE

SELECT * FROM TB_PEDIDO TBP
INNER JOIN TB_CLIENTE TBC
ON TBP.ID_CLIENTE = TBC.ID_CLIENTE;

SELECT TBC.NOME, TBP.PRECO, TBP.TIPO_ENTREGA FROM TB_CLIENTE TBC
INNER JOIN TB_PEDIDO TBP
ON TBP.ID_CLIENTE = TBC.ID_CLIENTE
WHERE TBP.TIPO_ENTREGA = 'Delivery'

SELECT TBC.NOME, TBZ.NOME FROM TB_CLIENTE TBC
INNER JOIN TB_PEDIDO TBP ON TBC.ID_CLIENTE = TBP.ID_CLIENTE
INNER JOIN TB_PEDIDO_PIZZA TBPP ON TBP.ID_PEDIDO = TBPP.ID_PEDIDO
INNER JOIN TB_PIZZA TBZ ON TBPP.ID_PIZZA = TBZ.ID_PIZZA

--***
SELECT TBC.NOME, TBZ.NOME, TBZ.CATEGORIA FROM TB_CLIENTE TBC
INNER JOIN TB_PEDIDO TBP ON TBC.ID_CLIENTE = TBP.ID_CLIENTE
INNER JOIN TB_PEDIDO_PIZZA TBPP ON TBP.ID_PEDIDO = TBPP.ID_PEDIDO
INNER JOIN TB_PIZZA TBZ ON TBPP.ID_PIZZA = TBZ.ID_PIZZA
WHERE TBZ.CATEGORIA LIKE '%Zero Lactose%'


SELECT TBC.NOME, SUM(TBP.PRECO) FROM TB_CLIENTE TBC
INNER JOIN TB_PEDIDO TBP ON TBC.ID_CLIENTE = TBC.ID_CLIENTE
GROUP BY TBC.NOME
ORDER BY SUM(TBP.PRECO) DESC



